version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npx sls deploy
workflows:
  deploy:
    jobs:
      - deploy:
          context: cf-worker
