name: Cloudflare
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Cloudflare Worker
    steps:
      - uses: actions/checkout@v2.0.0
      - name: install dependencies
        run: 'npm install'
      - name: build using wrangler
        run: 'npx wrangler build'
      - name: deploy using sls
        run: 'npx sls deploy'
        env:
          CLOUDFLARE_AUTH_EMAIL: ${{secrets.CLOUDFLARE_AUTH_EMAIL}}
          CLOUDFLARE_ACCOUNT_ID: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          CLOUDFLARE_ZONE_ID: ${{secrets.CLOUDFLARE_ZONE_ID}}
          CLOUDFLARE_AUTH_KEY: ${{secrets.CLOUDFLARE_AUTH_KEY}}
